### ISSUE TITLE
Items popping out of pipes

### ISSUE THREAD

**Issue by celsiusqc** [refinedmods/refinedpipes#48] opened 2021-01-08 00:09 UTC
Why are items popping out of pipes when using diamond pipes for example?

**Comment by Phoenix1355** [comment] 2021-01-21 22:57
I'm experiencing the same issue. The items are popping out of the pipes if the connected container is full. This seems like the logic for the diamond extractor is calculating the available space for the adjacent container incorrectly. Every time a few items are removed from a full container, extractors from other connected containers extract more items than there is space available in the target container, overflowing it and causing the additional items to drop.

So far, my only "fix" has been to set the extract item amount down to 1 item, so when an item pops out, it doesn't eject a whole stack or so. IMO, this _really_ needs to be fixed. The issue kinda makes the mod completely unusable, if you want to transport items in any way. And when it is implemented as the only pipe system in mod packs like the new FTB Direwolf20 1.16, with _no_ other alternatives other than Mekanism pipes, then, for me personally, it makes the whole mod pack sort of unplayable.

**Comment by attrib** [comment] 2021-01-30 14:56
Can confirm this as well, even with the basic pipe. It seems it doesn't remember that it already sent items to the storage, it keeps sending till its full. But it should already stop sending items when it should be full, when the last batch arrived.

My setup is fairly simple:

4 Furnaces connected at the back (fuel slot) to a chest with sapplings/sticks using basic item pipes and basic extractor.

Maybe its also related as the sticks/sapplings burn quickly, so the inventory gets updated often.
So it detects 56 sticks in the furnance and start sending one batch of sticks.
Then a stick is burned, but the 8 sticks send before didn't arrived yet, so its 55 sticks in the furnace and so it sends another batch as it didn't remembered there are already 8 sticks on the way.

So it should wait till 48 sticks are in the furnace to send another 8 sticks or the already sent items arrived and its below 56 again.

As you need to keep track of all stuff already on the way maybe as a quickfix instead of poping it out, it just sends the stuff back to the sender?

**Comment by raoulvdberge** [comment] 2021-03-06 11:47
Duplicate of #5

**Closed by raoulvdberge** 2021-03-06 11:47 UTC
