### ISSUE TITLE
Client crashes while trying to break a full fluid pipe

### ISSUE THREAD

**Issue by alexh2** [refinedmods/refinedpipes#51] opened 2021-01-30 18:33 UTC
When I try to break a fluid pipe with a fluid still inside, my client crashes. 

Modpack: Direwolf20 1.16 version 1.4.1
Refined Pipes version 0.5

[crash-2021-01-30_19.25.53-client.txt](https://github.com/refinedmods/refinedpipes/files/5898492/crash-2021-01-30_19.25.53-client.txt)

**Comment by OreCruncher** [comment] 2021-02-09 22:52
Just saw this randomly in my client.  No pipe breaking involved.  Just wandering around doing my thing.  (refinedpipes-0.5)

**Comment by lf-** [comment] 2021-02-15 13:25
I'm also getting this crash on DW20 1.16 v1.6.1

**Comment by OreCruncher** [comment] 2021-02-16 14:54
More info.  Playing DW20 1.6.0.  Got a message in chat from CCL indicating a rendering issue with a pipe.  The pipe in question had a basic extractor attachment.  I broke the pipe and placed it back down, and it rendered correctly.  When I attached the basic extractor it errored again.  Replaced with an improved version and it was fine.

**Comment by Louis-DR** [comment] 2021-02-18 11:29
I had the same crash : broke a pipe with lava inside and a diamond extractor attachement pointing up (I already removed the tank on top). I broke it with a fluxbore. The game crashed and I can't open the save now (contantly crashes).

**Comment by HellishINC** [comment] 2021-03-04 02:38
Forge has a config option to delete erroring tile entities on world load. Keep in mind it can kill a lot more than you expect.

`minecraft/saves/Uno/serverconfig/forge-server.toml`

```
	#Set this to true to remove any Entity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
	removeErroringEntities = false
	#Set this to true to remove any TileEntity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
	removeErroringTileEntities = false
```

**Comment by raoulvdberge** [comment] 2021-03-06 12:04
Duplicate of #12

**Closed by raoulvdberge** 2021-03-06 12:04 UTC
Labels: Bug
