### ISSUE TITLE
Game crash on breaking fluid pipe with tier 1 extractor

### ISSUE THREAD

**Issue by TronWoWGamer** [refinedmods/refinedpipes#82] opened 2021-10-26 20:07 UTC
Same problem as from this issue:   https://github.com/refinedmods/refinedpipes/issues/78

This was when water was in the pipe being extracted from a sink and I was trying to break the extractor and pipe on the sink so I could move them a block backward.  As was mentioned it happens in the modpack stacia expert. As soon as I break the Tier 2 fluid pipe, the game crashes. It hasn't occurred before, and there was neither an update of the modpack, nor an update of refined pipes (both on the most recent version).  It happens every time whether in survival or creative, so I have switched to creative to at least be able to delete the items, but I have to exit the modpack altogether every single piece of pipe that is broken.

This is the initial Java Exception at the beginning of the crash text.

java.lang.IllegalArgumentException: Cannot get property BooleanProperty{name=north, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{minecraft:air}
	at net.minecraft.state.StateHolder.func_177229_b(SourceFile:95) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ferritecore.fastmap.mixin.json:FastMapStateHolderMixin,pl:mixin:A}
	at com.refinedmods.refinedpipes.render.FluidPipeTileEntityRenderer.render(FluidPipeTileEntityRenderer.java:54) ~[?:0.5] {re:classloading}
	at com.refinedmods.refinedpipes.render.FluidPipeTileEntityRenderer.func_225616_a_(FluidPipeTileEntityRenderer.java:20) ~[?:0.5] {re:classloading}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228855_a_(TileEntityRendererDispatcher.java:101) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228857_b_(TileEntityRendererDispatcher.java:85) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher$$Lambda$38954/445338751.run(Unknown Source) ~[?:?] {}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228853_a_(TileEntityRendererDispatcher.java:118) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228850_a_(TileEntityRendererDispatcher.java:84) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1043) ~[?:?] 

[crash-2021-10-26_14.44.16-client.txt](https://github.com/refinedmods/refinedpipes/files/7421200/crash-2021-10-26_14.44.16-client.txt)

**Comment by MrPleasant-exe** [comment] 2021-11-13 05:48
Can second this, it seems to be an issue with water pipes, empty pipes are just fine.

**Comment by raoulvdberge** [comment] 2021-11-28 14:43
Duplicate of #63

**Closed by raoulvdberge** 2021-11-28 14:43 UTC
