### ISSUE TITLE
Game crash on breaking tier 2 fluid pipe

### ISSUE THREAD

**Issue by DasWeisSBroT** [refinedmods/refinedpipes#78] opened 2021-09-18 17:14 UTC
Seems like I have a problem with the refined pipes mod in the modpack stacia expert. As soon as I break the Tier 2 fluid pipe, the game crashes. It hasn't occured before, and there was neither an update of the modpack, nor an update of refined pipes (both on the most recent version
[crash-2021-09-18_18.38.10-client.txt](https://github.com/refinedmods/refinedpipes/files/7190362/crash-2021-09-18_18.38.10-client.txt)

**Comment by DasWeisSBroT** [comment] 2021-09-19 08:53
Edit: only when there is a Fluid in the pipe (in this case it was water)

**Comment by raoulvdberge** [comment] 2021-11-28 14:43
Duplicate of #63

**Closed by raoulvdberge** 2021-11-28 14:43 UTC
