### ISSUE TITLE
Crash when destroying fluid pipe while pumping

### ISSUE THREAD

**Issue by kurisubrooks** [refinedmods/refinedpipes#26] opened 2020-06-14 06:19 UTC
When breaking a fluid pipe that's pumping lava from a tank into a mekanism generator, the game crashes. Note: Optifine is installed and shaders are enabled (possible duplicate of #12?)

Crash log available here;
https://gist.github.com/kurisubrooks/03a29f01b83b1fc1604f7d4b037e90fa

**Comment by MrKusOw** [comment] 2021-01-07 11:09
can u pls fix this bug it is so annoying and because I have a lot of mods and so long to load the game.

**Comment by raoulvdberge** [comment] 2021-03-06 12:13
Duplicate of #12

**Closed by raoulvdberge** 2021-03-06 12:13 UTC
Labels: Bug
