### ISSUE TITLE
CCL caught a rendering exception

### ISSUE THREAD

**Issue by AmrasYavetil** [refinedmods/refinedpipes#54] opened 2021-02-22 12:11 UTC
When placing or rendering any pipe that has an extractor attachment, I receive the error message "CCL caught an exception rendering a block. See the log for info."

This applies on all pipes of item, fluid, and energy variants. The ONLY exception I could find was that the issue does not occur with ultimate tier extractors.

Log and screenshots attached: 

![2021-02-22_03 47 01](https://user-images.githubusercontent.com/64250162/108704830-64961680-74c1-11eb-84cf-5ebfa3d7f28f.png)
[latest.log](https://github.com/refinedmods/refinedpipes/files/6021727/latest.log)

**Comment by raoulvdberge** [comment] 2021-03-06 11:49
Duplicate of #44

**Closed by raoulvdberge** 2021-03-06 11:49 UTC
