### ISSUE TITLE
Extractors Won't Attach to Item Pipes

### ISSUE THREAD

**Issue by Boolyman** [refinedmods/refinedpipes#92] opened 2021-12-13 23:39 UTC
### Describe the bug

Extractors aren't attaching in the latest version.  They were attaching fine before this latest "texture" update.

### How can we reproduce this bug or crash?

Here is a video of me trying to attach the extractor to an item pipe

https://user-images.githubusercontent.com/24765883/145906234-10e5a3d2-2b32-4358-b596-bc68c7b84e30.mp4

### What Minecraft version is this happening on?

Minecraft 1.16.5

### What Forge version is this happening on?

36.2.19

### What Refined Pipes version is this happening on?

0.5.1

**Comment by Boolyman** [comment] 2021-12-13 23:50
I also rolled the version back and still cant attach the extractors.

**Comment by Boolyman** [comment] 2021-12-14 00:06
I looked through the logs and did find some refined pipes errors:

https://paste.gg/p/anonymous/c9f36ad8ab0f4bb1850fa3ab6ec70f05

**Comment by Boolyman** [comment] 2021-12-19 00:57
Is support for this mod dead or something?

**Comment by stooop** [comment] 2021-12-26 20:02
I ran into the same issue, and after a little testing, realized it's caused by some incompatibility with [Diet](https://www.curseforge.com/minecraft/mc-mods/diet). For now I've just disabled Diet, but that is obviously not an ideal solution.

**Comment by raoulvdberge** [comment] 2022-01-30 11:33
Duplicate of #100

**Closed by raoulvdberge** 2022-01-30 11:33 UTC
Labels: bug
