### ISSUE TITLE
[Request] A way to disable connections

### ISSUE THREAD

**Issue by aaronhowser1** [refinedmods/refinedpipes#43] opened 2021-01-03 11:29 UTC
As far as I know, there's no way to prevent connections to blocks. So you can't have two Item Pipes next to each other but not connected, and you can't have Pipes touch any inventory that you don't want items to enter.

**Comment by Darkere** [comment] 2021-01-03 11:46
Duplicate of #17

**Closed** 2021-01-03 12:03 UTC
