### ISSUE TITLE
Extractor Attachments send more than their destination can handle, spilling everything out onto the ground

### ISSUE THREAD

**Issue by aaronhowser1** [refinedmods/refinedpipes#52] opened 2021-02-06 23:39 UTC
https://user-images.githubusercontent.com/15698722/107132041-6cd73a80-68a1-11eb-9802-576d94b5c478.mp4

This is using `refinedpipes-0.5`

**Comment by raoulvdberge** [comment] 2021-03-06 11:46
Duplicate of #5

**Closed by raoulvdberge** 2021-03-06 11:46 UTC
