### ISSUE TITLE
Energy pipes not extracting energy until cell is full

### ISSUE THREAD

**Issue by Hunter00064** [refinedmods/refinedpipes#46] opened 2021-01-06 11:14 UTC
Energy pipes aren't extracting energy from a redstone flux cell until its completely full or I stop the input(Put input to 0).

After some testing it seemed like if you set the input more than the output it wouldn't push energy out until the cell was full, or if your pipes didn't have a high enough energy transfer rate.

For example, Tier 3 pipes, if you set input above 8k and output above that, it would not extract energy until the cell is full.

While setting the input to 7500 and output to <8k it would push energy through(Not at a fast rate, if I had to guess it would be 500RF/t)

Idk anything about modding for MC but it seems like when a side is set to output, it can also input energy through that side aswell.

**Comment by Hunter00064** [comment] 2021-01-06 11:15
I just tested it, that is the issue, an output slot is acting as both input and output so the pipes are just taking energy just to put it back into the cell

**Comment by ZL1LAC** [comment] 2021-01-07 06:33
I'm also having the same issue, running Direwolf20 pack, but it doesn't seem to work with extreme reactors 2.

**Comment by Hunter00064** [comment] 2021-01-07 10:27
They work on extreme reactors 2 for me(Make sure you are using the 'Active' tap and not the 'Passive'

**Comment by ZL1LAC** [comment] 2021-01-10 12:36
Direwolf20 has confirmed in his video this as bug and will be fixed in the next version.

**Comment by raoulvdberge** [comment] 2021-11-28 14:45
Closing this as I'm assuming this is not caused by Refined Pipes?

**Closed** 2021-11-28 14:44 UTC
